import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Classroom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} flex text-neutral-950`}>
        <div className="hidden md:block left-0 fixed top-0">
          <Sidebar />
        </div>
        <div className="w-full ml-0 md:ml-16">{children}</div>
      </body>
    </html>
  );
}
